name: shadow
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.1
  - psycopg[binary,pool]
  - psycopg2-binary
  - celery
  - aiofiles
  - aiohttp
  - hvac
  - pandas
  - pydicom
  - pyyaml
  - highdicom
  - SimpleITK
  - nibabel
  - scipy
  - numpy
  - scikit-learn
  - scikit-image
  - matplotlib
  - Connected-Components-3D
  - huggingface_hub


